DROP TABLE IF EXISTS samples;
DROP TABLE IF EXISTS progress;

CREATE TABLE samples (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    filepath TEXT UNIQUE NOT NULL,
    x INTEGER NOT NULL DEFAULT 0,
    y INTEGER NOT NULL DEFAULT 0,
    width INTEGER NOT NULL DEFAULT 0,
    height INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 0,
    updated_date TIMESTAMP DEFAULT (DATETIME('now', 'localtime'))
);
CREATE INDEX IF NOT EXISTS id_idx ON samples(id);

CREATE TABLE progress (
    pos INTEGER PRIMARY KEY,
    total INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS pos_idx ON progress(pos);

INSERT INTO progress(pos, total) VALUES(0, 0);
